export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const FETCH_MOVIES_ERROR = "FETCH_MOVIES_ERROR";

export const FETCH_SYNOPSIS_START = "FETCH_SYNOPSIS_START";
export const FETCH_SYNOPSIS_SUCCESS = "FETCH_SYNOPSIS_SUCCESS";
export const FETCH_SYNOPSIS_ERROR = "FETCH_SYNOPSIS_ERROR";

export const ADD_TO_HISTORY = "ADD_TO_HISTORY";